# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PixelLocator
                                 A QGIS plugin
 This plugin allows to identify the image coordinates of a pixel.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-18
        copyright            : (C) 2024 by Ariane Müting
        email                : mueting@uni-potsdam.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PixelLocator class from file PixelLocator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pixel_locator import PixelLocator
    return PixelLocator(iface)
