# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PixelLocator
                                 A QGIS plugin
 This plugin allows to identify the image coordinates of a pixel.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Ariane Müting
        email                : mueting@uni-potsdam.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
import qgis.utils
from qgis.gui import QgsMapTool
from qgis.core import QgsProject
# Initialize Qt resources from file resources.py
from .resources import *
import numpy as np

# Import the code for the DockWidget
from .pixel_locator_dockwidget import PixelLocatorDockWidget
import os.path

class GetLocationTool(QgsMapTool): #inherits QgsMapTool
    """Return point coordinate upon click."""
    
    def __init__(self, iface, dockwidget):
        """ Constructor"""
        
        QgsMapTool.__init__(self, iface.mapCanvas())
        self.iface = iface
        self.setCursor(Qt.WhatsThisCursor)
        self.dockwidget = dockwidget
        
    def canvasReleaseEvent(self, event): 
        #check active layer on every new click to check if it has changed
        self.layer = self.iface.activeLayer()
        #TODO: what happens if active layer is of type vector?
        point = self.toLayerCoordinates(self.layer, event.pos())
        
        #get upper left corner and resolution of active layer
        ext = self.layer.extent()
        xmin = ext.xMinimum()
        ymax = ext.yMaximum()
        
        #make sure point is within active layer extent
        if (point.x() >= xmin) and (point.x() <= ext.xMaximum()) and (point.y() >= ext.yMinimum()) and (point.y() <= ymax): 
            xres = self.layer.rasterUnitsPerPixelX()
            yres = self.layer.rasterUnitsPerPixelY()
            
            #convert to image coordinates
            xcoord = abs(point.x() - xmin) / xres
            ycoord = abs(point.y() - ymax) / yres
            
            #update text in dockwidget
            self.dockwidget.xcoord.setText(f"   {int(np.round(xcoord, 0))}")
            self.dockwidget.ycoord.setText(f"   {int(np.round(ycoord, 0))}")
        
        else:
            self.dockwidget.xcoord.setText(" ")
            self.dockwidget.ycoord.setText(" ")

class PixelLocator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PixelLocator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Pixel Locator')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'PixelLocator')
        self.toolbar.setObjectName(u'PixelLocator')

        #print "** INITIALIZING PixelLocator"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PixelLocator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/pixel_locator/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Get image coordinates of pixel.'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING PixelLocator"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None.unsetMapTool(my_tool)

        self.pluginIsActive = False
        


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD PixelLocator"

        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&Pixel Locator'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING PixelLocator"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = PixelLocatorDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            
        self.canvas = self.iface.mapCanvas()

        get_coordinates = GetLocationTool(self.iface, self.dockwidget)
        self.canvas.setMapTool(get_coordinates)

    #TODO: update cursor
    #TODO: show floating pixel location below cursor
